### ISSUE TITLE
play.api.db.evolutions.InconsistentDatabase

### ISSUE THREAD

**Issue by baram204** [baram204/blog-study#10]
play.api.db.evolutions.InconsistentDatabase: Fatal execution error, caused by Database 'default' is in an inconsistent state![An evolution has not been applied properly.

```

[[37minfo[0m] c.z.h.HikariDataSource - HikariCP pool db is starting.
[[37minfo[0m] c.z.h.HikariDataSource - HikariCP pool db is starting.
[[37minfo[0m] a.e.s.Slf4jLogger - Slf4jLogger started
[[36mdebug[0m] s.j.J.statement - Preparing insert statement (returning: ID): insert into "PROJECT" ("NAME")  values (?)
[[36mdebug[0m] s.j.J.statement - Preparing statement: select "ID", "NAME" from "PROJECT"
[[37minfo[0m] c.z.h.p.HikariPool - HikariCP pool db is shutting down.
[[37minfo[0m] c.z.h.HikariDataSource - HikariCP pool db is starting.
[[31merror[0m] p.a.d.e.DefaultEvolutionsApi - Table "POST" already exists; SQL statement:
create table POST (
"ID" bigint generated by default as identity(start with 1) not null primary key,
"TITLE" varchar not null,
"POSTEDAT" varchar not null,
"CONTENT" varchar not null,
"AUTHORID" integer NOT NULL,
FOREIGN KEY (AUTHORID) REFERENCES USER (ID)
) [42101-192] [ERROR:42101, SQLSTATE:42S01]
[[31merror[0m] p.a.d.e.DefaultEvolutionsApi - Table "POST" already exists; SQL statement:
create table POST (
"ID" bigint generated by default as identity(start with 1) not null primary key,
"TITLE" varchar not null,
"POSTEDAT" varchar not null,
"CONTENT" varchar not null,
"AUTHORID" integer NOT NULL,
FOREIGN KEY (AUTHORID) REFERENCES USER (ID)
) [42101-192] [ERROR:42101, SQLSTATE:42S01]
[info] ModelSpecs2Spec
[info] 
[info] An item  should
[info]   + be inserted during the first test case
[error]   ! and not exist in the second test case
[error]    play.api.db.evolutions.InconsistentDatabase: Fatal execution error, caused by Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.] (EvolutionsApi.scala:276)
[error] play.api.db.evolutions.DatabaseEvolutions.checkEvolutionsState(EvolutionsApi.scala:276)
[error] play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:126)
[error] play.api.db.evolutions.DatabaseEvolutions.resetScripts(EvolutionsApi.scala:288)
[error] play.api.db.evolutions.Evolutions$.cleanupEvolutions(Evolutions.scala:207)
[error] testhelpers.EvolutionHelper$.clean(EvolutionHelper.scala:10)
[error] models.ModelSpecs2Spec.after(ModelSpecs2Spec.scala:18)
[error] models.ModelSpecs2Spec.after(ModelSpecs2Spec.scala:14)
[info] 
[info] 
[info] 
[info] Total for specification ModelSpecs2Spec
[info] Finished in 547 ms
[info] 2 examples, 5 expectations, 0 failure, 1 error, 3 skipped
[info] 
[info] UserRepoSpec:
[info] An item
[[37minfo[0m] c.z.h.HikariDataSource - HikariCP pool db is starting.
[[31merror[0m] p.a.d.e.DefaultEvolutionsApi - Table "POST" already exists; SQL statement:
create table POST (
"ID" bigint generated by default as identity(start with 1) not null primary key,
"TITLE" varchar not null,
"POSTEDAT" varchar not null,
"CONTENT" varchar not null,
"AUTHORID" integer NOT NULL,
FOREIGN KEY (AUTHORID) REFERENCES USER (ID)
) [42101-192] [ERROR:42101, SQLSTATE:42S01]
[info] - should be inserted during the first test case *** FAILED ***
[info]   play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
[info]   at play.api.db.evolutions.DatabaseEvolutions.checkEvolutionsState(EvolutionsApi.scala:276)
[info]   at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:126)
[info]   at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:102)
[info]   at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:117)
[info]   at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:82)
[info]   at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:53)
[info]   at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:99)
[info]   at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
[info]   at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
[info]   at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
[info]   ...
[[31merror[0m] p.a.d.e.DefaultEvolutionsApi - Table "POST" already exists; SQL statement:
create table POST (
"ID" bigint generated by default as identity(start with 1) not null primary key,
"TITLE" varchar not null,
"POSTEDAT" varchar not null,
"CONTENT" varchar not null,
"AUTHORID" integer NOT NULL,
FOREIGN KEY (AUTHORID) REFERENCES USER (ID)
) [42101-192] [ERROR:42101, SQLSTATE:42S01]
[info] Exception encountered when attempting to run a suite with class name: models.UserRepoSpec *** ABORTED ***
[info]   play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
[info]   at play.api.db.evolutions.DatabaseEvolutions.checkEvolutionsState(EvolutionsApi.scala:276)
[info]   at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:126)
[info]   at play.api.db.evolutions.DatabaseEvolutions.resetScripts(EvolutionsApi.scala:288)
[info]   at play.api.db.evolutions.Evolutions$.cleanupEvolutions(Evolutions.scala:207)
[info]   at testhelpers.EvolutionHelper$.clean(EvolutionHelper.scala:10)
[info]   at models.UserRepoSpec.afterEach(UserRepoSpec.scala:16)
[info]   at org.scalatest.BeforeAndAfterEach$class.afterEach(BeforeAndAfterEach.scala:205)
[info]   at models.UserRepoSpec.afterEach(UserRepoSpec.scala:12)
[info]   at org.scalatest.BeforeAndAfterEach$class.afterEach(BeforeAndAfterEach.scala:220)
[info]   at models.UserRepoSpec.afterEach(UserRepoSpec.scala:12)
[info]   ...
[info] ModelScalaTestSpec:
[info] An item
[[37minfo[0m] c.z.h.HikariDataSource - HikariCP pool db is starting.
[[31merror[0m] p.a.d.e.DefaultEvolutionsApi - Table "POST" already exists; SQL statement:
create table POST (
"ID" bigint generated by default as identity(start with 1) not null primary key,
"TITLE" varchar not null,
"POSTEDAT" varchar not null,
"CONTENT" varchar not null,
"AUTHORID" integer NOT NULL,
FOREIGN KEY (AUTHORID) REFERENCES USER (ID)
) [42101-192] [ERROR:42101, SQLSTATE:42S01]
[info] - should be inserted during the first test case *** FAILED ***
[info]   play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
[info]   at play.api.db.evolutions.DatabaseEvolutions.checkEvolutionsState(EvolutionsApi.scala:276)
[info]   at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:126)
[info]   at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:102)
[info]   at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:117)
[info]   at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:82)
[info]   at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:53)
[info]   at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:99)
[info]   at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
[info]   at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
[info]   at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
[info]   ...
[[31merror[0m] p.a.d.e.DefaultEvolutionsApi - Table "POST" already exists; SQL statement:
create table POST (
"ID" bigint generated by default as identity(start with 1) not null primary key,
"TITLE" varchar not null,
"POSTEDAT" varchar not null,
"CONTENT" varchar not null,
"AUTHORID" integer NOT NULL,
FOREIGN KEY (AUTHORID) REFERENCES USER (ID)
) [42101-192] [ERROR:42101, SQLSTATE:42S01]
[info] Exception encountered when attempting to run a suite with class name: models.ModelScalaTestSpec *** ABORTED ***
[info]   play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
[info]   at play.api.db.evolutions.DatabaseEvolutions.checkEvolutionsState(EvolutionsApi.scala:276)
[info]   at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:126)
[info]   at play.api.db.evolutions.DatabaseEvolutions.resetScripts(EvolutionsApi.scala:288)
[info]   at play.api.db.evolutions.Evolutions$.cleanupEvolutions(Evolutions.scala:207)
[info]   at testhelpers.EvolutionHelper$.clean(EvolutionHelper.scala:10)
[info]   at models.ModelScalaTestSpec.afterEach(ModelScalaTestSpec.scala:18)
[info]   at org.scalatest.BeforeAndAfterEach$class.afterEach(BeforeAndAfterEach.scala:205)
[info]   at models.ModelScalaTestSpec.afterEach(ModelScalaTestSpec.scala:14)
[info]   at org.scalatest.BeforeAndAfterEach$class.afterEach(BeforeAndAfterEach.scala:220)
[info]   at models.ModelScalaTestSpec.afterEach(ModelScalaTestSpec.scala:14)
[info]   ...
[info] PostRepoSpec:
[info] Post
[[37minfo[0m] c.z.h.HikariDataSource - HikariCP pool db is starting.
[[31merror[0m] p.a.d.e.DefaultEvolutionsApi - Table "POST" already exists; SQL statement:
create table POST (
"ID" bigint generated by default as identity(start with 1) not null primary key,
"TITLE" varchar not null,
"POSTEDAT" varchar not null,
"CONTENT" varchar not null,
"AUTHORID" integer NOT NULL,
FOREIGN KEY (AUTHORID) REFERENCES USER (ID)
) [42101-192] [ERROR:42101, SQLSTATE:42S01]
[info] - should 사용자 키와 함께 생성될 수 있다 *** FAILED ***
[info]   play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
[info]   at play.api.db.evolutions.DatabaseEvolutions.checkEvolutionsState(EvolutionsApi.scala:276)
[info]   at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:126)
[info]   at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:102)
[info]   at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:117)
[info]   at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:82)
[info]   at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:53)
[info]   at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:99)
[info]   at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
[info]   at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
[info]   at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
[info]   ...
[[31merror[0m] p.a.d.e.DefaultEvolutionsApi - Table "POST" already exists; SQL statement:
create table POST (
"ID" bigint generated by default as identity(start with 1) not null primary key,
"TITLE" varchar not null,
"POSTEDAT" varchar not null,
"CONTENT" varchar not null,
"AUTHORID" integer NOT NULL,
FOREIGN KEY (AUTHORID) REFERENCES USER (ID)
) [42101-192] [ERROR:42101, SQLSTATE:42S01]
[info] Exception encountered when attempting to run a suite with class name: models.PostRepoSpec *** ABORTED ***
[info]   play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
[info]   at play.api.db.evolutions.DatabaseEvolutions.checkEvolutionsState(EvolutionsApi.scala:276)
[info]   at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:126)
[info]   at play.api.db.evolutions.DatabaseEvolutions.resetScripts(EvolutionsApi.scala:288)
[info]   at play.api.db.evolutions.Evolutions$.cleanupEvolutions(Evolutions.scala:207)
[info]   at testhelpers.EvolutionHelper$.clean(EvolutionHelper.scala:10)
[info]   at models.PostRepoSpec.afterEach(PostRepoSpec.scala:18)
[info]   at org.scalatest.BeforeAndAfterEach$class.afterEach(BeforeAndAfterEach.scala:205)
[info]   at models.PostRepoSpec.afterEach(PostRepoSpec.scala:13)
[info]   at org.scalatest.BeforeAndAfterEach$class.afterEach(BeforeAndAfterEach.scala:220)
[info]   at models.PostRepoSpec.afterEach(PostRepoSpec.scala:13)
[info]   ...
[info] ScalaTest
[info] Run completed in 3 seconds, 314 milliseconds.
[info] Total number of tests run: 3
[info] Suites: completed 0, aborted 3
[info] Tests: succeeded 0, failed 3, canceled 0, ignored 0, pending 0
[info] *** 3 SUITES ABORTED ***
[info] *** 3 TESTS FAILED ***
[error] Error: Total 8, Failed 3, Errors 4, Passed 1
[error] Error during tests:
[error] 	models.PostRepoSpec
[error] 	models.ModelSpecs2Spec
[error] 	models.ModelScalaTestSpec
[error] 	models.UserRepoSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4 s, completed May 17, 2017 5:44:50 PM
```

**Comment by baram204** [comment]
play.api.db.evolutions.InconsistentDatabase: Fatal execution error, caused by Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.] 

에볼루션이 적절하게 적용되지 않았다. 

p.a.d.e.DefaultEvolutionsApi - Table "POST" already exists; 

POST 테이블이 이미 있다.

------------
즉, 에볼루션 적용이 매번 될 때마다, POST 테이블 생성하려고 하는데 이미 있다.

```
 --- !Downs

DROP TABLE TASK;
DROP TABLE PROJECT;
drop table "USER" if exists;
```

Down 작업에 POST 테이블 제거가 빠져있다.

각 test 케이스 끝나면 다음 구문이 실행되면서 에볼루션 Down 작업이 되는데.. 거기에 POST 테이블 제거가 빠져있던 것

```scala
  override def afterEach() = EvolutionHelper.clean()
```
